FROM golang:1.21-alpine

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

RUN apk update && apk add --no-cache postgresql-client

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

COPY run_migrations.sh .

RUN chmod +x run_migrations.sh

CMD ["./run_migrations.sh"]
